#!/usr/bin/env python3

# (C) 2015 - 2017 by Tomasz bla Fortuna
# License: MIT

"""
Entry point for DataStalker tool.
"""

try:
    from datastalker import main
except ImportError:
    print("Unable to find and import the `datastalker' module - make sure it's")
    print("installed in your site-packages/dist-packages directories or available")
    print("at PYTHONPATH environment")
    print()
    raise

if __name__ == "__main__":
   main.run()
